# Generated by Django 3.2.9 on 2021-11-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='upvotes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
