# Generated by Django 3.2.9 on 2021-11-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='score',
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
